version: "3.1"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hg
      MYSQL_USER: hg
      MYSQL_PASSWORD: hg
    ports:
      - 3306:3306
    volumes:
      - "dbdata:/var/lib/mysql"

  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      DB_URL: hg:hg@(mysql:3306)/hg?parseTime=true
    restart: always
    command: "/app/start.sh mysql:3306"

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:8080
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  dbdata:
